apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 8081
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: ralph.maurer@gibb.ch
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresdb-secret
              key: postgres-password
        - name: ME_CONFIG_POSTGRESDB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: postgresdb-configmap
              key: database_url
      
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: LoadBalancer
